### ISSUE TITLE
--help exits program in debug mode!

### ISSUE THREAD

**Issue by ghost** [nodeca/argparse#100]
combining addHelp and debug will not raise the help message as an exception but will instead exit the program:

```
var argparse = require('argparse');

var ARGP = new argparse.ArgumentParser({
    addHelp:true,
    debug: true,
});

try {
    ARGP.parseArgs(['--help']);
} catch (err) {
    // This block is not hit
    console.log('Captured Error')
    console.log(err.message)
}
```

See: https://github.com/nodeca/argparse/blob/503675573c206ac6447f8c56ac9abe6a7b8b3f85/lib/action/help.js#L46

**Comment by ava-dylang** [comment]
I can get the desired behavior with this monkeypatch:
```
var monkeypatch_argphelp = require('argparse/lib/action/help');
monkeypatch_argphelp.prototype.call = function(parser){parser.error('help')}
```

**Comment by rlidwka** [comment]
`debug` option is deprecated in 2.0, so this is no longer relevant

Please override 'exit' function to stop parser from exiting. Something like this:

```js
class MyParser extends argparse.ArgumentParser {
    exit() {
        throw 'EXIT'
    }
}

const parser = new MyParser()
parser.parse_args('-h')
```
