### ISSUE TITLE
Make it possible to override ArgumentParser.prototype._printMessage

### ISSUE THREAD

**Issue by bolinfest** [nodeca/argparse#106]
Currently, the logic in `ArgumentParser` that calls through to `_printMessage` hardcodes `process.stdout` and `process.stderr` as the streams that are written to in various places.

Ideally, it should be possible to use other streams for `stdout` and `stderr`. This should be configurable in the top-level `ArgumentParser` that the user creates, and any instances of `ArgumentParser` that are created via its subparsers should inherit this behavior.

**Comment by puzrin** [comment]
Is this feature supported in python's package?

**Comment by bolinfest** [comment]
Sort of...I would say that Python's `argparse` doesn't do this particularly well. Take a look at [these signatures](https://docs.python.org/dev/library/argparse.html#printing-help):

```
ArgumentParser.print_usage(file=None)
ArgumentParser.print_help(file=None)
```

If you call those methods yourself, then you can specify the stream, though if you look at `argparse.py`, you can see that, internally, `ArgumentParser` always invokes these methods without specifying `file`, so it defaults to `sys.stdout`. Although you can subclass `ArgumentParser` and override `print_usage()` and `print_help()` for an individual instance of `ArgumentParser`, it is not easy to do the same for every `ArgumentParser` created from that one via its subparsers.

I would say that this is a design mistake. I am trying to use `argparse` as a library in a daemon that takes requests, runs the input through `argparse`, and sends the stdout/stderr back to the user. As such, I want to create a new `ArgumentParser` for each request, each with its own stream to capture stdout/stderr.

As such, I cannot redefine `ArgumentParser.prototype._printMessage` globally because each call needs to be parameterized with its own stdout/stderr. Currently, I am doing the following as a workaround, which is gross:

```
import {ArgumentParser} from 'argparse';
import invariant from 'assert';

// This is my current workaround for
// https://github.com/nodeca/argparse/issues/100.
ArgumentParser.prototype.exit = function(status, message) {
  if (message) {
    if (status === 0) {
      this._printMessage(message);
    } else {
      this._printMessage(message, process.stderr);
    }
  }

  // Do not exit because that will kill the daemon.
  // process.exit(status);
};

/**
 * @param {Array<string>} args Program arguments.
 * @param {Function} printOut function for writing to stdout that is unique to
 *     each request.
 * @param {Function} printErr function for writing to stderr that is unique to
 *     each request.
 */
function processRequest(printOut, printErr) {
  function patchArgumentParser(parser) {
    parser._printMessage = function(message, stream) {
      if (message != null) {
        if (stream === process.stderr) {
          printErr(message);
        } else {
          printOut(message);
        }
      }
    };
  }

  const parser = new ArgumentParser({
    addHelp: true,
    debug: true, // Parse error throws instead of calling process.exit().
    prog: PROGRAM_NAME,
    version: PROGRAM_VERSION,
  });
  patchArgumentParser(parser);

  const subparserKey = 'subparserName';
  const subparsers = parser.addSubparsers({dest: subparserKey});
  const originalAddParser = subparsers.addParser;
  subparsers.addParser = function(name, options) {
    const subParser = originalAddParser.call(subparsers, name, options);
    invariant(subParser instanceof ArgumentParser);
    patchArgumentParser(subParser);
    return subParser;
  };

  // ...Add parsers to subparsers... 

  let parsedArgs;
  try {
    parsedArgs = parser.parseArgs(args);
  } catch (e) {
    printErr(e.message);
    return;
  }

  // If we got this far, then parsedArgs is valid and we can now proceed.
  // Though figuring out which subparser was activated is also a problem
  // in the current implementation. I filed this as
  // https://github.com/nodeca/argparse/issues/103, but this is my current
  // workaround:
  const subparser = parsedArgs[subparserKey];
  if (subparser === SUBCOMMAND_NAME || subparser === SUBCOMMAND_ALIAS) {
    doSubcommand(parsedArgs, printOut, printErr);
  }

  // ...check subparser against other registered commands...
}
```

I spent more time than I care to admit looking at various arg parsing libraries in Node. The most popular ones ([`yargs`](https://www.npmjs.com/package/yargs) and [`commander`](https://www.npmjs.com/package/commander)) both have major design issues that make them unsuitable for my use case:

* `yargs` makes heavy use of singletons in its design, which is hard to undo: https://github.com/yargs/yargs/issues/347
* `commander` has a call to `process.exit()` that cannot easily be fixed by monkey-patching (and seems unresponsive to pull requests, as a project): https://github.com/tj/commander.js/issues/575

I was very excited when I discovered your project because it is so close to being exactly what I need out of the box! Obviously I was able to work around my issue with some hacks, but I would prefer to contribute and fix this for others.

**Comment by puzrin** [comment]
We need some reasonable tradeoff. Because when project is declared as port, any deviations from mainstream are not welcome. If you can suggest, how to simplify your life with minimal intrusion to existing logic, that's discussable.

I think it worth to wait about 1-2 weeks, until we finish v2.0 beta and continue after. Also, i'd suggest to kick python's guys about better streams (files?)  support in mainstream.

**Comment by bolinfest** [comment]
@puzrin But your support for `debug` is custom to your Node package and is not present in Python's argparse, correct? Would PRs be welcome that affect debug mode only?

I'll try to come up with a concrete, satisfactory proposal once v2.0 is available.

**Comment by puzrin** [comment]
AFAIK, we have no special support for `debug`. But i could forget something, because this code was done several years ago :). The only code for debug i know is in your pending PR.

> Would PRs be welcome that affect debug mode only?

Key point is the minimal total count of deviations. The nature of each deviation is not principal. With 1-2 small differences we still can refer to original docs. But that can become a problem on bigger diffs.

It would be also good to get some comments, why node.js reguires different behaviour in debug mode. If that's something platform-specific  - that's discussable.

**Comment by rlidwka** [comment]
> Although you can subclass `ArgumentParser` and override `print_usage()` and `print_help()` for an individual instance of `ArgumentParser`, it is not easy to do the same for every `ArgumentParser` created from that one via its subparsers.

Subparsers have the same class as your main instance. So you subclass main parser, then subparsers automatically get the same changes.

> But your support for `debug` is custom to your Node package and is not present in Python's argparse, correct?

Yes, it was intended for tests, and it will be removed in future versions.

> I'll try to come up with a concrete, satisfactory proposal once v2.0 is available.

2.0 is now out. Closing this, please reopen if it's still an issue.
