### ISSUE TITLE
Electron and required quotes when passing args with value

### ISSUE THREAD

**Issue by Ciantic** [nodeca/argparse#107]
I know this maybe a problem with electron, but some may come here also. 

I'm seeing this, given following code:

``` javascript
let argParser = new ArgumentParser({
    version: "0.0.1",
    addHelp: true,
    description: "My App",
});
argParser.addArgument(["-a", "--appUrl"], {
    help : "Application url (defaults to http://localhost:6002)",
    defaultValue : "http://localhost:6002/"
});
let args = argParser.parseArgs();
```

If I try to call it normally (without quotes), I get this:

```
myapp-electron.exe --appUrl http://example.com
usage: --appUrl [-h] [-v] [-a APPURL]
--appUrl: error: Unrecognized arguments: http://example.com
```

However it works with quotes:

```
myapp-electron.exe "--appUrl http://example.com"
```

Noteworthy also that args parsing works for some reason correctly when running through electron npm app, e.g.:

```
electron . -a http://example.com
```

So something in built electron app (.exe in Windows) makes argument parsing wonky.

**Comment by puzrin** [comment]
No ideas, sorry. I think it's better to report this to electron bundler tracker.

**Comment by M3TIOR** [comment]
It could be the issue I tried to resolve in my commit #139 , Perhaps do some more tests to see if it's just the last argument being parsed that doesn't catch. Note how it prints ```Usage: --appUrl ...```, I think the library is parsing the first argument as your application name.

**Comment by rlidwka** [comment]
I've made an attempt at fixing it, so please tell me if this works:

https://github.com/nodeca/argparse/blob/f1a60eebdc487708085398da7e3fbcddd396d7b4/argparse.js#L91-L95

If it doesn't, please reopen this issue, and PR is very welcome.

You can also fix it on your end by manually passing argv to `parse_args()` (which you can tweak as you like).

Note: it works in normal `electron`, so maybe this is a bundler error?
