### ISSUE TITLE
argparse.REMAINDER

### ISSUE THREAD

**Issue by edemaine** [nodeca/argparse#110]
In the Python module, you set `nargs = argparse.REMAINDER` to capture the remaining arguments.  In this module, it seems you need to use `nargs: argparse.Const.REMAINDER`.  Any particular reason for the addition of `Const`?  This confused me for a while...  At the least, the documentation should mention the discrepancy.

**Comment by puzrin** [comment]
This port was done several years ago.

- we could miss something
- we could skip some rare features due lack of time
- something could change for this time

Nobody intended to confuse users. Of cause, if you find any deviations - PR description to readme. That will be useful on next resync with upstream.

**Comment by edemaine** [comment]
OK, created PR #111.

**Comment by puzrin** [comment]
Thanks!
