### ISSUE TITLE
aliases should preserve the canonical command

### ISSUE THREAD

**Issue by richburdon** [nodeca/argparse#114]
When you set an alias, it works, but the stored command name is the actual alias not the required command, which seems to default the purpose -- since you have to process each of the aliases downstream.

**Comment by puzrin** [comment]
1. How should it work (in python)?
2. Please, provide code sample how to reproduce

**Comment by richburdon** [comment]
Example:

~~~~
    commands.addParser('status',  { addHelp: true, aliases: ['stat'] });
~~~~

When invoking the command via "stat" (i.e., the alias), the value should be "status". Otherwise the handler needs logic to catch all of the aliases (breaking encapsulation).

**Comment by rlidwka** [comment]
Which value are you talking about?

Can you show a full example that we can copy-paste and run, where it makes any difference?

Closing this for now.
