### ISSUE TITLE
API Question: List of options & Option with no value

### ISSUE THREAD

**Issue by corybill** [nodeca/argparse#117]
Two Questions:

1. Is it possible to pass a list of items under a single option?
2. Do i always need to pass in a value with the option or can I just use the option as a flag with no value after it.

Thanks.

**Comment by corybill** [comment]
Well.. I just found nargs. Is that the expected way to do this?

**Comment by puzrin** [comment]
Please, look into original python's argparse docs and samples. I don't rememver details.
