### ISSUE TITLE
When running in a compiled app (e.g. Electron), the program name is the first element, not the second

### ISSUE THREAD

**Issue by burnpanck** [nodeca/argparse#128]
Therefore, the default `argv` as `process.argv.slice(2)` is incorrect in this case. 

This might also be the reason of #107.

**Comment by puzrin** [comment]
Nobody claimed this package to work in electron, but PR welcome.

**Comment by burnpanck** [comment]
Sure, I'm not saying it should :-). Just trying to provide a note for other people running into this issue, to help them getting started. It seems clear that `process.argv.slice(2)` is not always the correct thing to do, but it's not at all clear how to detect when to only discard the first argument and when to discard the first two. I have no good answer to that. In our workaround we simply first try to skip only the first, and if parsing fails, try again with skipping two. But that only works because we do not have positional arguments. In fact, I guess that python will see the same issue (though compiling/packaging is possibly less common there). In python's argparse, they seem to default to skipping just one, if I read the code correctly: https://github.com/python/cpython/blob/ec10b70ea66e738ccb5c28f75a9c5d2b1c197de7/Lib/argparse.py#L1758

**Comment by rlidwka** [comment]
I've made an attempt at fixing it, so please tell me if this works:

https://github.com/nodeca/argparse/blob/f1a60eebdc487708085398da7e3fbcddd396d7b4/argparse.js#L91-L95

If it doesn't, please reopen this issue, and PR is very welcome.

You can also fix it on your end by manually passing argv to `parse_args()` (which you can tweak as you like).

Note: it works in normal `electron`, so maybe this is a bundler error?

**Comment by rlidwka** [comment]
*Turns out, trying to autodetect this like shown above breaks every other interpreter.*

Anyway, in node.js `process.argv[0]` should always be a path to the interpreter. It is done this way in `coffee`, `typescript` and every other node.js wrapper I know about. Very different from python where interpreter name is left out.

If electron compiler does this other way, it is a bug in electron compiler and should be reported there imho. 

As a workaround, in your electron application you can pass argv (any argv you like) manually into parser like this:

```js
let parser = argparse.ArgumentParser()
parser.parse_args([ '-h' ])
```

**Comment by 1j01** [comment]
Full code to support Electron packaged and unpackaged cases, in an Electron app's main process code:
```js
// Compare command line arguments:
// - unpackaged (in development):          "path/to/electron.exe" "src/electron-main.js" "--my-args"
//   (or via package.json's main field):   "path/to/electron.exe" "." "--my-args"
// - packaged (usually in production):     "path/to/MyApp.exe" "--my-args"
const { app } = require('electron');
const argsArray = process.argv.slice(app.isPackaged ? 1 : 2);
const args = parser.parse_args(args_array);
```

`yargs` handles this [in its `hideBin`](https://github.com/yargs/yargs/blob/0c95f9c79e1810cf9c8964fbf7d139009412f7e7/lib/utils/process-argv.ts#L24) using Electron's [`process.defaultApp`](https://github.com/electron/electron/blob/main/docs/api/process.md#processdefaultapp-readonly), first checking for [`process.versions.electron`](https://github.com/electron/electron/blob/main/docs/api/process.md#processversionselectron-readonly).
So theoretically this is all that should be required to handle Electron seamlessly in argparse, as well as Node:
```js
function get_argv() {
    const isElectronApp = "electron" in process.versions;
    const isPackagedElectronApp = isElectronApp && !process.defaultApp;
    return process.argv.slice(isPackagedElectronApp ? 1 : 2);
}
```
But I see [the code now in argparse](https://github.com/nodeca/argparse/blob/a645a9a9d3d0a347f383d0b795859e67dfae6ad8/argparse.js#L93) is `return process.argv.slice(1)`, which seems like it wouldn't work in Node?
Node is typically:
```
"node" "my-script.js" "--my-args"
```
So the script needs to be ignored as well.
I don't know if that applies to `ts-node` or `coffee` CLIs, or `#!/usr/bin/env node` hashbang scripts.
