### ISSUE TITLE
test fromfile.js object elements shifted

### ISSUE THREAD

**Issue by bill1812** [nodeca/argparse#130]
test recursive reading arguments from files under windows 7
node 8.14.1
npm 6.5.0
how can I fix this?
  ...
    args = parser.parseArgs([ '-a', 'B', '@recursive', 'Y', 'Z' ]);
    assert.deepEqual(args, { a: 'A', x: 'hello world!', y: [ 'Y', 'Z' ] });
  ...

  1) from file
       test recursive reading arguments from files:

      AssertionError [ERR_ASSERTION]:
      Namespace {
        a: '\r',
        x: 'A\r',
        y: [ 'hello world!', 'Y', 'Z' ]
      } deepEqual {
        a: 'A',
        x: 'hello world!',
        y: [ 'Y', 'Z' ]
      }

      + expected
      - actual

       {
      -  "a": "\r"
      -  "x": "A\r"
      +  "a": "A"
      +  "x": "hello world!"
         "y": [
      -    "hello world!"
           "Y"
           "Z"
         ]
       }

      at Context.<anonymous> (test\fromfile.js:40:12)
  ...
    args = parser.parseArgs([ 'X', '@recursive', 'Z', '-a', 'B' ]);
    assert.deepEqual(args, { a: 'B', x: 'X', y: [ 'hello world!', 'Z' ] });
  ...
  2) from file
       test recursive reading arguments from files:

      AssertionError [ERR_ASSERTION]:
      Namespace {
        a: 'B',
        x: 'X',
        y: [ 'A\r', 'hello world!', 'Z' ]
      } deepEqual {
        a: 'B',
        x: 'X',
        y: [ 'hello world!', 'Z' ]
      }

      + expected
      - actual

       {
         "a": "B"
         "x": "X"
         "y": [
      -    "A\r"
           "hello world!"
           "Z"
         ]
       }
      at Context.<anonymous> (test\fromfile.js:42:12)

**Comment by rlidwka** [comment]
We've ported everything from scratch based on python 3.9 (to be released as argparse version 2.0), so this test no longer exists.

Please open a new issue if anything is still broken.
