### ISSUE TITLE
pass object in cmd using argparse 

### ISSUE THREAD

**Issue by bipinshukla** [nodeca/argparse#131]
hello folks, can anyone tell me is this possible to pass args as object
let me show my code sample 

                parser.addArgument(
                        ['-p', '--params'],
                        {
                       
                        required: true,
                        help: 'folder name'
                        }
                );
now my problem is that i want params as object like params.echo=1 params.next=2 etc but it giving output like params='echo=1'

**Comment by rlidwka** [comment]
Uhm... I have no idea what you wanted to ask. Please re-open this issue if it is still relevant with more clear examples.
