### ISSUE TITLE
Patch older versions of ArgParse as well

### ISSUE THREAD

**Issue by DarrenMack-OD** [nodeca/argparse#134]
The DEV of [remarkable](https://github.com/jonschlinkert/remarkable) is refusing to update his dependency on ArgParse because he believes you should patch ALL versions of ArgParse, therefore he shouldn't have to update to the latest version to get rid of some security warning triggered by older versions of ArgParse in NPM...

While I don't understand this mentality, is this something you could do?

**Comment by puzrin** [comment]
No ideas. This package has only one dependency (i don't count devdeps). If you can tell exactly where the problem is - i can check what can be done.

**Comment by puzrin** [comment]
Ah, missed world "older" in title. Sorry, no plans to support ancient versions. All versions have stable/compatible API. If someone don't like to change deps - that should not become my problem.

Also, you can switch to https://github.com/markdown-it/markdown-it. It's more actual.
