### ISSUE TITLE
Nested ArgumentGroup

### ISSUE THREAD

**Issue by piranna** [nodeca/argparse#143]
`ArgumentGroup` allow to call `addArgumentGroup()`, but after that, arguments are not shown in the help. It should be possible to do it by showing the arguments as nested.

**Comment by puzrin** [comment]
It this implemented in upstream?

**Comment by piranna** [comment]
What do you mean upstream? At the Python version?

**Comment by puzrin** [comment]
Yes. That's a port of pyton's code (~ exact copy), requests to diverge are not accepted. If you mean missed feature - i'd like to understand it in original.

PS. Also, you can write your custom help formatter, that's a common approach.

**Comment by rlidwka** [comment]
Please provide an example. Any example that we can run, check its output and discuss.

Closing this for now.
