### ISSUE TITLE
add_argument fails to fail when provided with invalid arguments

### ISSUE THREAD

**Issue by marvin1up** [nodeca/argparse#147]
parser.addArgument(['-o', '--out'], {
      help: 'Output file for metadata, default dist/__metadata__.js',
      defaultValue: 'dist/__metadata__.js',
      // required: true,
      useless: 11,
    });

This example succeeds, even though `useless` is not a valid option.  Even though this is pretty typical for JS libraries, its wrong here just as it is elsewhere.  This particular issue is particularly problematic since the argument `default` has apparently been renamed to `defaultValue` so specifying an incorrect option `default` is silently ignored.

**Comment by rlidwka** [comment]
Fixed in 2.0 (now `default` stays `default` as it is in python, and unrecognized arguments are being thoroughly complained about).
