### ISSUE TITLE
Implementation of default and required are inconsistent with Python implememtation.

### ISSUE THREAD

**Issue by marvin1up** [nodeca/argparse#148]
parser.addArgument(['-o', '--out'], {
      help: 'Output file for metadata, default dist/__metadata__.js',
      defaultValue: 'dist/__metadata__.js',
      required: true,
    });

In the python implementation (and logically) if an argument is specified as `required`, AND a `defaultValue` IS provided (`default` in the original python) the argument need not be specified in the argument list.  But npm argparse flags that as an exception.

**Comment by puzrin** [comment]
Full rewrite (in master) has no such problem anymore.
