### ISSUE TITLE
v2 cannot be used with ts-node anymore

### ISSUE THREAD

**Issue by timocov** [nodeca/argparse#150]
When you run scripts written in TypeScript with `ts-node` `process.argv` looks like

```js
[
  '/path/to/project-root/node_modules/ts-node/dist/bin.js',
  '/path/to/project-root/path/to/script-name.ts',
  // ... all other cli args here
]
```

In 1.x version it was parsed correctly, but since 2.0 it throws `bin.js: error: unrecognized arguments: /path/to/project-root/path/to/script-name.ts`. Probably the issue is [somewhere here](https://github.com/nodeca/argparse/blob/f1a60eebdc487708085398da7e3fbcddd396d7b4/argparse.js#L93), because the first arg isn't `process.execPath`. I'm not sure whether it's `ts-node`'s issue, please let me know if it is so.

**Comment by rlidwka** [comment]
Fixed in https://github.com/nodeca/argparse/commit/10fd15512ae6c3450696246463966e35d019fc27. Definitely not `ts-node` issue.

**Comment by timocov** [comment]
Thanks!
