### ISSUE TITLE
add_parser with parents results in conflicting option for help

### ISSUE THREAD

**Issue by ahippler** [nodeca/argparse#152]
Subparsers with parents are broken with v2. It adds the help command multiple times and throws an Error on runtime.

minimal example:
```js
const { ArgumentParser } = require("argparse");

const parser = new ArgumentParser();
const subparsers = parser.add_subparsers({ dest: "command" });

const subparsers1 = subparsers.add_parser("1");
const subparsers2 = subparsers.add_parser("2", {
  parents: [subparsers1],
});

parser.parse_args();
```

output:
```
node_modules/argparse/argparse.js:2398
        throw new ArgumentError(action, sub(message, conflict_string))
        ^

ArgumentError: argument -h/--help: conflicting option strings: -h, --help
    at _ArgumentGroup._handle_conflict_error (node_modules/argparse/argparse.js:2398:15)
    at _ArgumentGroup._check_conflict (node_modules/argparse/argparse.js:2389:30)
    at _ArgumentGroup._add_action (node_modules/argparse/argparse.js:2199:14)
    at _ArgumentGroup._add_action (node_modules/argparse/argparse.js:2456:24)
    at ArgumentParser._add_container_actions (node_modules/argparse/argparse.js:2274:35)
    at new ArgumentParser (node_modules/argparse/argparse.js:2660:18)
    at _SubParsersAction.add_parser (node_modules/argparse/argparse.js:1781:22)
    at Object.<anonymous> (test.js:7:32)
    at Module._compile (internal/modules/cjs/loader.js:1075:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1096:10) {
  _argument_name: '-h/--help',
  _message: 'conflicting option strings: -h, --help'
}
```

**Comment by baparham** [comment]
In Python at least, it was recommended to turn off the help of the parent to avoid this sort of thing. Perhaps try `addHelp: false` in the parent parser options?

**Comment by ahippler** [comment]
Yes. This is the workaround i use for the moment. But this will not create a --help option for the parent command.

**Comment by baparham** [comment]
Funny enough, I just came across a use case that I think I need for myself, so perhaps I'll see if I can try fixing it.

**Comment by puzrin** [comment]
Is this case specific to js-port or the same in upstream? If the same - should no be reported here.

**Comment by baparham** [comment]
Interesting question. What role does `js-port` play here? Is that the mechanism or tool used to port the python implementation to javascript?

**Comment by puzrin** [comment]
> Interesting question. What role does `js-port` play here? Is that the mechanism or tool used to port the python implementation to javascript?

Just a term. This package is ported manually, with all benefits and disadvantages of original.

**Comment by puzrin** [comment]
> same error for Python 3.8.5 argparse==1.4.0

Let's close then. I've added issue template with clarifications https://github.com/nodeca/argparse/blob/master/.github/ISSUE_TEMPLATE.md.

We are not experts about how to use argparse, we focused on how to make this package close to original. StackOverflow already has all possible recipes for python, which can be used here.

**Comment by baparham** [comment]
Thanks for clarifying, I understand what you meant now, and since it fails it python implementation than it makes sense that this is not a bug here.
