### ISSUE TITLE
exit_on_error 'false' flag not respected when error in positional arguments

### ISSUE THREAD

**Issue by aksharpatel47** [nodeca/argparse#155]
argparse version: 2.0.1

### Reproducible Code:

**index.js**
```js
const argparse = require("argparse");

const parser = new argparse.ArgumentParser({ exit_on_error: false });

parser.add_argument("subCommand", {
  choices: ["api"],
});
parser.add_argument("utility", { choices: ["sub_api"], });
parser.add_argument("action", {
  choices: ["help", "create", "update", "delete"],
});

const stArgs = "api sub_api".split(
  " "
);

try {
  const args = parser.parse_args(stArgs);
} catch (error) {
  console.log("error message caught");
}

```

**Current Output**
```
usage: index.js [-h] {api} {sub_api} {help,create,update,delete}
index.js: error: the following arguments are required: action
```
The process exists after pushing the above message on the console.

**Expected Output**
```
error message caught
```

Looking at the source code, in the error function implementation in argparse.js, the exit_on_error flag needs to be checked before running the exit method.
https://github.com/nodeca/argparse/blob/174bd80df5b45519475b9e2f611090b5b453b243/argparse.js#L3641-L3658

**Comment by puzrin** [comment]
https://github.com/python/cpython/blob/3.9/Lib/argparse.py#L2564 there is nothing of such kind in original.

Did you searched how they solve this issue?

**Comment by aksharpatel47** [comment]
Hi @puzrin. I see they don't handle it in the original library too. To accomplish this without changing anything in this project we can extend the ArgumentParser and override the error method.

Feel free to close this issue and the pr if you think it is outside the scope of this library. Thanks for your time.

**Comment by msikma** [comment]
I ran into this myself and worked around it like this:

```ts
class CustomArgumentParser extends ArgumentParser {
  error(message: string) {
    if (message.includes('the following arguments are required')) {
      return
    }
    return super.error(message)
  }
}
```
