### ISSUE TITLE
Please add defaultValue usage example

### ISSUE THREAD

**Issue by erjoalgo** [nodeca/argparse#167]
I didn't see it in the README and wasn't sure if it was supported.

**Comment by puzrin** [comment]
`defaultValue` was in v1 and now is `default` see https://github.com/nodeca/argparse/blob/master/doc/migrate_v1_to_v2.md.

v2 is close to original as much as possible, see original docs.

**Comment by erjoalgo** [comment]
I don't think my request was understood. As a user, I don't care if there's a `v1` or `v2`. I'd just like to see current usage of the useful feature to set default arguments featured prominently in the docs, without having to dig too deep or looking at the source. My first impression was that setting default arguments was not supported.

As you can see from the python argparse docs, I can get a glimpse of most of the useful available features by just looking at a few lines of code of a concise example:

![22-Apr-2022-16:35:56](https://user-images.githubusercontent.com/5349288/164789997-e61ec1ea-5c23-42aa-8432-3c4204929c8f.png)

**Comment by puzrin** [comment]
I don't understand you, sorry

**Comment by erjoalgo** [comment]
I'm stumped... what part is unclear?

**Comment by puzrin** [comment]
i don't understand what you expect from me to do.

**Comment by erjoalgo** [comment]
#168

**Comment by erjoalgo** [comment]
Ping.

**Comment by rlidwka** [comment]
> As you can see from the python argparse docs, I can get a glimpse of most of the useful available features by just looking at a few lines of code of a concise example:

I've put that exact example from python in readme:

https://github.com/nodeca/argparse/blob/a645a9a9d3d0a347f383d0b795859e67dfae6ad8/README.md#example

So I hope it's more clear now.

**Comment by rlidwka** [comment]
https://github.com/nodeca/argparse/commit/a645a9a9d3d0a347f383d0b795859e67dfae6ad8
