### ISSUE TITLE
Change the "filename.js" in the usage/help message

### ISSUE THREAD

**Issue by d4n5h** [nodeca/argparse#174]
Is there a way to change the file name in the usage/help message?
![image](https://github.com/nodeca/argparse/assets/1638614/c1c3504b-e81c-4f6a-b2fa-9f8c48a8f971)

**Comment by salderma** [comment]
Would like some guidance here as well.  When an app is bundled with yarn, the "executable" is renamed from `bundle.js` and further when packaged into a binary with npx, argparse utilizes `bundle.js` as the program name for the usage output instead of whatever the binary file was named.

**Comment by rlidwka** [comment]
Use `prog` argument for ArgumentParser:

```js
const { ArgumentParser } = require('argparse')
const parser = new ArgumentParser({ prog: 'your-file-name' })
parser.print_help()
// prints: `usage: your-file-name [-h]`
```

**Comment by d4n5h** [comment]
Thank you @rlidwka 👍
