### ISSUE TITLE
ArgumentError class

### ISSUE THREAD

**Issue by hpaulj** [nodeca/argparse#49]
The Python code creates an `ArgumentError` class.  This JS implementation uses an `argumentErrorHelper()`, which formats the same message, but returns a (plain) `Error` object.  Below is an ArgumentError subclass that is a little closer in style to the Python.  It could also be used in a  `err instanceof ArgumentError` test if needed.

```
function ArgumentError(argument, message) {
  this.argument = argument || null;
  this.message = message || "";
  this.name = "ArgumentError";
  Error.captureStackTrace(this, this);
  this.argumentName = this.argument.getName();
  }
}
util.inherits(ArgumentError, Error);
ArgumentError.prototype.toString = function () {
  var astr;
  if (this.argumentName) {
    astr = "argument \"" + this.argumentName + "\": " + this.message;
  } else {
    astr = "" + this.message;
  }
  return this.name + ": " + astr;
};
```

**Comment by rlidwka** [comment]
Everything is rewritten with ES6 (to be released as argparse 2.0), so it's now `class ArgumentError extends Error {}`. I hope it fixes any issues with instanceof and such.
