### ISSUE TITLE
ArgumentTypeError

### ISSUE THREAD

**Issue by hpaulj** [nodeca/argparse#50]
Python creates an `ArgumentTypeError` class, which a user-defined-type function can use.  It does not add any functionality, but `parser._getValue()` uses the error class to distinguish between errors that get a standardized message: `invalid ... value` (ValueError, TypeError), and ones whose is message is passed on (ArgumentTypeError).  In effect `ArgumentTypeError` gives the user more control of the error message.  For example in a FileType, IOErrors should be passed on to the user.

In issue #45, named types get the standardized message, while anonymous ones get a customized one.  This could be changed to distinguish between TypeErrors and ArgumentTypeErrors.

```
function ArgumentTypeError(msg) {
  Error.captureStackTrace(this, this);
  this.message = msg || 'Argument Error';
  this.name = 'ArgumentTypeError';
}
util.inherits(ArgumentTypeError, Error);
```

**Comment by rlidwka** [comment]
I've ported everything from scratch based on python 3.9 (to be released as argparse version 2.0), ArgumentTypeError is now there.
