### ISSUE TITLE
Change in Python3.4 on when the type function is called on the defaultValue

### ISSUE THREAD

**Issue by hpaulj** [nodeca/argparse#52]
Python development issues 12776 and 15906
http://bugs.python.org/issue12776
"When specifying a function to be called in type keyword argument of add_argument(), the function is actually called twice (when a default value is set and then when the argument is given)."

In the current dev Python version, this patch moves a `self._get_value(action, default)` from the start of `parse_known_args` to near the end of `_parse_known_args`, after it is known whether the default value is needed or not.  This prevents unnecessary evaluation of the argument default value.  For types like `float` this does not matter, but for `FileType` we don't want to open the default file if it is not needed.

I just raised the issue of what happens with a positional argument with nargs='_':
`add_argument('foo', type=FileType('r'), default='anyfile', nargs='_')`

This is the biggest change in the Python argparse development pipeline.  We should keep an eye on what develops.

**Comment by rlidwka** [comment]
If it fixed in python, it *should* now be fixed here as well.

Please re-open this issue if it isn't.
