### ISSUE TITLE
Failure to recognize negative scientific notation (with nargs:2)

### ISSUE THREAD

**Issue by hpaulj** [nodeca/argparse#55]
On stackoverflow I came across an argparse.py issue that also affects this version.  It has to do with recognizing negative numbers like `-2e4`.  The `negativeNumberMatcher` does not handle scientific notation.

However the issue only rises in special circumstances such as a `nargs:2` case, and there are work arounds.

```
ArgumentParser = require('argparse').ArgumentParser

parser = new ArgumentParser({debug:true});
parser.addArgument(['--xlim'], {nargs: 2, type: 'float'});

args = parser.parseArgs(['--xlim', '-.002', '1e4']);
console.log(args);
// { xlim: [ -0.002, 10000 ] }

args = parser.parseArgs(['--xlim', '-2e3', '1e4'])
// TypeError: argument "--xlim": Expected 2 argument(s)
```

http://stackoverflow.com/questions/9025204/python-argparse-issue-with-optional-arguments-which-are-negative-numbers
http://bugs.python.org/issue9334
may be a related issue (parsing `['-a','-one','-two']` where `(['-a',{nargs:2})`.  That is, should '-one' be interpreted as an optional, or as an argument to '-a'?

**Comment by rlidwka** [comment]
Argparse 2.0 was ported from scratch based on python 3.9.0. We aimed to keep source code as close as possible to the original, so this change didn't make it in.

Is it used by anybody? If so, maybe bug python developers again, issue still not resolved over there.
