### ISSUE TITLE
argparse: optional subparsers

### ISSUE THREAD

**Issue by hpaulj** [nodeca/argparse#58]
Python Issue 9253

This issue requested the ability to make the subparsers argument optional.  In the latest development release that has become the default.  Previous versions had a test near the end of `_parseKnownArgs`:

```
// if we didn't use all the Positional objects, there were too few
// arg strings supplied.
if (positionals.length > 0) {
  self.error('too few arguments');
}
```

which had the effect of warning if a subparsers argument was missing, even though the corresponding `action.required` attribute was `false`.  This was test was dropped in the latest development version, leaving it up to the following test to flag missing arguments:

```
// make sure all required actions were present
self._actions.forEach(function (action) {
  if (action.required) {
    if (_.indexOf(seenActions, action) < 0) {
      self.error(format('Argument "%s" is required', action.getName()));
    }
  }
});
```

I have submitted a Python patch 
http://bugs.python.org/issue9253#msg186695
that makes `ActionSubparsers.required = true` by default.  I also added custom a `getName()` method to this subclass to give a meaningful name (in case `dest` or `metvar` are not set).  The Python code also had problems formatting the error message when `getName` return a `None`, but I don't think that's an issue in the javascript code.

**Comment by rlidwka** [comment]
We will port it when patch gets accepted to python, closing this ticket for now (can't fix it independently here).

Please check python patch again, I think it only needs a test suite?
