### ISSUE TITLE
argparse doesn't allow optionals within positionals

### ISSUE THREAD

**Issue by hpaulj** [nodeca/argparse#60]
Python issue http://bugs.python.org/issue14191

Some unix coders are used to freely intermixing optionals and positionals.   `optparse`, which  `argparse` is supposed to replace, parses all of the optionals, and puts everything else in an `extras` array.   This is like `parseKnownArgs` but with freer intermixing.

A proposed solution is to write a `parser.parseIntermixedArgs` that does a 2 step parse, first parse the input with only the conditionals arguments, and then parse the `extras` with the positionals.

**Comment by rlidwka** [comment]
`parse_intermixed_args` is ported from python as part of argparse.js 2.0
