### ISSUE TITLE
'-ku' and '-uk' give different results than '-k -u'

### ISSUE THREAD

**Issue by hpaulj** [nodeca/argparse#61]
http://bugs.python.org/issue16142
ArgumentParser inconsistent with parse_known_args

Users want:

```
parser.add_argument('-k','--known',action='store_true')
print(parser.parse_known_args(['-k','-u']))
print(parser.parse_known_args(['-ku']))
print(parser.parse_known_args(['-uk']))
```

to all  produce the same output:

```
(Namespace(known=True), ['-u'])
```

Currently '-ku' gives an error, and '-uk' goes into the `extras`.

I submitted a patch to fix the '-ku' case (without breaking any tests).

**Comment by rlidwka** [comment]
This is still not fixed in python.

We aim to have a strict port of python version, and there is no way to fix this without deviating too much.

Please bug python devs again if this is important, closing this for now. If they fix it, we'll port it.
