### ISSUE TITLE
Single character options can be concatenated with their arguments

### ISSUE THREAD

**Issue by hotpxl** [nodeca/argparse#79]
I found this behavior in the source code `argument_parser.js:816`. It is explicitly made to act this way. But it's not what the Python version is doing. I don't think single character options could be concatenated with their arguments. Consider the following example:

    parser.addArgument(['-start-date'], ...);
    parser.addArgument(['-sum'], ...);

Now I got an ambiguity and it just won't work. Could you guys make it work like the Python one? Thanks!

**Comment by puzrin** [comment]
> Could you guys make it work like the Python one? Thanks!

Honestly, i have no plans to spend time for this project. It is mature and "good enougth". All changes last 2 years were cosmetic.

If anyone decide to resync with newer mainstream -  PR will be accepted. But i can't promiss any changes from my side in near of far future.

**Comment by hotpxl** [comment]
Cool! I'll see if I could work on that.

Thanks!

**Comment by hotpxl** [comment]
btw, thank you for this great tool. definitely much handier than any other command line parsing tool outside.
