### ISSUE TITLE
storeTrue and store for one argument?

### ISSUE THREAD

**Issue by dalanmiller** [nodeca/argparse#94]
I'm looking to add a flag where if no values are given such as `--flag` it just stores `true` and if values are given `--flag value` then they are stored as normal. 

Is there a way to do this with argparse?

**Comment by rlidwka** [comment]
You can put all arguments into an array like this:

```js
parser.add_argument('--flag', { nargs: '?', action: 'append' })
```

And then manually check whats inside.

Or you can create a custom action (class CustomAction extends argparse.Action) and implement necessary logic in there.

(`nargs: '?'` means "zero or one argument")
