### ISSUE TITLE
Support For Optional Subparsers

### ISSUE THREAD

**Issue by malamoney** [nodeca/argparse#99]
It would be helpful to be able to make subcommands optional. Instead we get "error: too few arguments"

I believe this is supported in the latest python version.

**Comment by puzrin** [comment]
I think, there are no need to create separate issues for every feature, included to "sync with upstream"

Currently we have no plans to do such sync, but PRs from volunteers with full sync is welcome.

**Comment by harlentan** [comment]
Optional Subparsers is usefull. Is there any plan to support this feature?

**Comment by rlidwka** [comment]
> I believe this is supported in the latest python version.

We've ported everything from python 3.9. If it works there, it now works here.
